//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAY()
        {
            this.CHITIETDONDATHANG = new HashSet<CHITIETDONDATHANG>();
        }
    
        public string Magiay { get; set; }
        public string Tengiay { get; set; }
        public int Size { get; set; }
        public decimal Giagiay { get; set; }
        public string Mota { get; set; }
        public string Anhbia { get; set; }
        public System.DateTime Ngaycapnhat { get; set; }
        public int Soluongton { get; set; }
        public string Maloai { get; set; }
        public Nullable<bool> Hot { get; set; }
        public string MaSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANG { get; set; }
        public virtual LOAIGIAY LOAIGIAY { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
